# Generated by Django 6.1 on 2026-08-29 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_order_product_orderitem_order_products_userprofile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
